### ISSUE TITLE
Very limited example :p

### ISSUE THREAD

**Issue by GideonUng** [rust-analyzer/rust-project.json-example#1]
working on my own rust/c/cpp/glsl build tool and was hoping to find some example stuff...
well

**Comment by akesling** [comment]
Is there supposed to be a `rust-project.json` file in this repo?  That's what https://rust-analyzer.github.io/manual.html lead me to believe.

**Comment by CAD97** [comment]
> Is there supposed to be a rust-project.json file in this repo?

AIUI, as the [docs](https://rust-analyzer.github.io/manual.html#rust-analyzer.linkedProjects) say,

> <dl><dt class="hdlist1">rust-analyzer.linkedProjects (default: <code>[]</code>)</dt><dd><p>Disable project auto-discovery in favor of explicitly specified set of projects.</p><p>Elements must be paths pointing to <code>Cargo.toml</code>, <code>rust-project.json</code>, <b>or JSON objects in <code>rust-project.json</code> format</b> [emphasis mine].</p></dd></dl>

the object set in `settings.json` here is an object in `rust-project.json` format. Alternatively, it could just be a string path to a `rust-project.json` file with the same contents as are inlined here.
